apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service-demo
  template:
    metadata:
      labels:
        app: api-service-demo
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:1.0
          args:
            - -text=hello
          ports:
            - containerPort: 5678

