apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustom-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kustom-web
  template:
    metadata:
      labels:
        app: kustom-web
    spec:
      containers:
        - name: web
          image: nginx:1.27
          ports:
            - containerPort: 80

