apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
spec:
  completions: 1
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pi
          image: perl:5.34
          command:
            - perl
            - -Mbignum=bpi
            - -wle
            - print bpi(1000)

