apiVersion: v1
kind: Pod
metadata:
  name: secure-nginx
  namespace: secure-apps
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
  containers:
    - name: nginx
      image: nginx:1.27
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

