apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrong
  template:
    metadata:
      labels:
        app: wrong
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80

