apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: app
      image: nginx
      env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: app.name
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: app.version